version: '3'

services:
  web:
    build: .
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - "8081:80"
    links:
      - db
    volumes:
      - ./app:/var/www/html/

  db:
    image: mariadb
    restart: always
    volumes:
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ciblog
    ports:
      - "8889:3306"
